var json_TouristAttractionLocations_4 = {
"type": "FeatureCollection",
"name": "TouristAttractionLocations_4",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "name": null, "name_en": null, "amenity": "parking", "man_made": null, "shop": null, "tourism": null, "opening_ho": null, "beds": null, "rooms": null, "addr_full": null, "addr_house": null, "addr_stree": null, "addr_city": null, "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 244310456.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.475174599927868, -24.985858699819119 ] } },
{ "type": "Feature", "properties": { "name": null, "name_en": null, "amenity": "parking", "man_made": null, "shop": null, "tourism": null, "opening_ho": null, "beds": null, "rooms": null, "addr_full": null, "addr_house": null, "addr_stree": null, "addr_city": null, "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 5163826782.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.2686991002833, -25.169504299583707 ] } },
{ "type": "Feature", "properties": { "name": null, "name_en": null, "amenity": "parking", "man_made": null, "shop": null, "tourism": null, "opening_ho": null, "beds": null, "rooms": null, "addr_full": null, "addr_house": null, "addr_stree": null, "addr_city": null, "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 5163826783.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.268207600100709, -25.169882200103416 ] } },
{ "type": "Feature", "properties": { "name": "Tindlovu Berg-en-Dal", "name_en": null, "amenity": "restaurant", "man_made": null, "shop": null, "tourism": null, "opening_ho": "Mo-Su 07:00-21:00", "beds": null, "rooms": null, "addr_full": null, "addr_house": null, "addr_stree": null, "addr_city": null, "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 2221645655.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.450477899935208, -25.42660410039889 ] } },
{ "type": "Feature", "properties": { "name": "Mugg & Bean", "name_en": null, "amenity": "restaurant", "man_made": null, "shop": null, "tourism": null, "opening_ho": "Mo-Su 07:00-21:00", "beds": null, "rooms": null, "addr_full": null, "addr_house": null, "addr_stree": null, "addr_city": null, "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 1165781350.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.916411700339722, -25.118738599806477 ] } },
{ "type": "Feature", "properties": { "name": "Nkhulu Cafe", "name_en": null, "amenity": "cafe", "man_made": null, "shop": null, "tourism": null, "opening_ho": null, "beds": null, "rooms": null, "addr_full": null, "addr_house": null, "addr_stree": null, "addr_city": null, "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 11263238253.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.769204199913929, -24.996869499827483 ] } },
{ "type": "Feature", "properties": { "name": "Cattle Baron Takeaway", "name_en": null, "amenity": "fast_food", "man_made": null, "shop": null, "tourism": null, "opening_ho": "Mo-Su,PH 07:00-21:00", "beds": null, "rooms": null, "addr_full": null, "addr_house": null, "addr_stree": null, "addr_city": null, "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 12007353186.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.592412300187561, -24.992536999682727 ] } },
{ "type": "Feature", "properties": { "name": "Kruger Station", "name_en": null, "amenity": "restaurant", "man_made": null, "shop": null, "tourism": null, "opening_ho": "Mo-Su 07:00-21:00", "beds": null, "rooms": null, "addr_full": null, "addr_house": "1350", "addr_stree": null, "addr_city": "Skukuza", "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 915680273.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.595629800175175, -24.993593200365865 ] } },
{ "type": "Feature", "properties": { "name": "Ntandanyathi", "name_en": null, "amenity": "parking", "man_made": null, "shop": null, "tourism": null, "opening_ho": null, "beds": null, "rooms": null, "addr_full": null, "addr_house": null, "addr_stree": null, "addr_city": null, "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 961672978.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.959364000248456, -25.207289100411629 ] } },
{ "type": "Feature", "properties": { "name": "Nhlanguleni Parking", "name_en": null, "amenity": "parking", "man_made": null, "shop": null, "tourism": null, "opening_ho": null, "beds": null, "rooms": null, "addr_full": null, "addr_house": null, "addr_stree": null, "addr_city": null, "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 452968932.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.656383400273739, -24.710108100108698 ] } },
{ "type": "Feature", "properties": { "name": "Satara", "name_en": null, "amenity": "restaurant", "man_made": null, "shop": null, "tourism": null, "opening_ho": null, "beds": null, "rooms": null, "addr_full": null, "addr_house": null, "addr_stree": null, "addr_city": null, "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 5163787347.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.779662799998277, -24.393255999864436 ] } },
{ "type": "Feature", "properties": { "name": "Phabeni gate parking", "name_en": null, "amenity": "parking", "man_made": null, "shop": null, "tourism": null, "opening_ho": null, "beds": null, "rooms": null, "addr_full": null, "addr_house": null, "addr_stree": null, "addr_city": null, "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 411704806.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.241426500033015, -25.025006800023732 ] } },
{ "type": "Feature", "properties": { "name": "Numbi Gate Parking", "name_en": null, "amenity": "parking", "man_made": null, "shop": null, "tourism": null, "opening_ho": null, "beds": null, "rooms": null, "addr_full": null, "addr_house": null, "addr_stree": null, "addr_city": null, "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 2096013616.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.19861959981472, -25.155515999863439 ] } },
{ "type": "Feature", "properties": { "name": "Tshokwane Picnic Site", "name_en": null, "amenity": "restaurant", "man_made": null, "shop": null, "tourism": null, "opening_ho": null, "beds": null, "rooms": null, "addr_full": null, "addr_house": null, "addr_stree": null, "addr_city": null, "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 2500814678.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.858919999758257, -24.786193700378931 ] } },
{ "type": "Feature", "properties": { "name": null, "name_en": null, "amenity": "bench", "man_made": null, "shop": null, "tourism": null, "opening_ho": null, "beds": null, "rooms": null, "addr_full": null, "addr_house": null, "addr_stree": null, "addr_city": null, "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 5389453737.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.895021800315874, -24.857753600048568 ] } },
{ "type": "Feature", "properties": { "name": null, "name_en": null, "amenity": "cafe", "man_made": null, "shop": null, "tourism": null, "opening_ho": null, "beds": null, "rooms": null, "addr_full": null, "addr_house": null, "addr_stree": null, "addr_city": null, "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 12007353263.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.531971399760323, -25.286544100429865 ] } },
{ "type": "Feature", "properties": { "name": null, "name_en": null, "amenity": "cafe", "man_made": null, "shop": null, "tourism": null, "opening_ho": null, "beds": null, "rooms": null, "addr_full": null, "addr_house": null, "addr_stree": null, "addr_city": null, "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 12007353275.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.531757499608943, -25.286523399835005 ] } },
{ "type": "Feature", "properties": { "name": null, "name_en": null, "amenity": "bench", "man_made": null, "shop": null, "tourism": null, "opening_ho": null, "beds": null, "rooms": null, "addr_full": null, "addr_house": null, "addr_stree": null, "addr_city": null, "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 11556251569.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.377454500225042, -25.213205699683272 ] } },
{ "type": "Feature", "properties": { "name": null, "name_en": null, "amenity": "bench", "man_made": null, "shop": null, "tourism": null, "opening_ho": null, "beds": null, "rooms": null, "addr_full": null, "addr_house": null, "addr_stree": null, "addr_city": null, "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 11556251669.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.517245799853811, -25.167236400039769 ] } },
{ "type": "Feature", "properties": { "name": null, "name_en": null, "amenity": "bench", "man_made": null, "shop": null, "tourism": null, "opening_ho": null, "beds": null, "rooms": null, "addr_full": null, "addr_house": null, "addr_stree": null, "addr_city": null, "source": null, "name_af": null, "name_nr": null, "name_st": null, "name_nso": null, "name_ssw": null, "name_ts": null, "name_tn": null, "name_ve": null, "name_xh": null, "name_zu": null, "osm_id": 11556251670.0, "osm_type": "nodes" }, "geometry": { "type": "Point", "coordinates": [ 31.513167600104737, -25.039170999941632 ] } }
]
}
